"""Add face_encoding to inmate

Revision ID: 46a84b4dd0dc
Revises: 7b13e22da811
Create Date: 2025-06-09 16:06:01.463443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a84b4dd0dc'
down_revision = '7b13e22da811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inmate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_encoding', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inmate', schema=None) as batch_op:
        batch_op.drop_column('face_encoding')

    # ### end Alembic commands ###
