"""Add Alert model with inmate_id FK

Revision ID: 7080b32a1220
Revises: 001450b33b1b
Create Date: 2025-04-23 19:54:59.587991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7080b32a1220'
down_revision = '001450b33b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resolved', sa.Boolean(), nullable=True))
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.FLOAT(), nullable=True))
        batch_op.drop_column('resolved')
        batch_op.drop_column('level')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
