"""create facial_embedding table

Revision ID: 7f70919eb449
Revises: 3186b744a729
Create Date: 2025-09-03 19:19:46.775458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f70919eb449'
down_revision = '3186b744a729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facial_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.PickleType(), nullable=False),
    sa.Column('predicted_id', sa.Integer(), nullable=True),
    sa.Column('inmate_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inmate_id'], ['inmate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facial_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facial_embedding_predicted_id'), ['predicted_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facial_embedding_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facial_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facial_embedding_timestamp'))
        batch_op.drop_index(batch_op.f('ix_facial_embedding_predicted_id'))

    op.drop_table('facial_embedding')
    # ### end Alembic commands ###
